language: android
android:
    components:
        - platform-tools
        - tools

        - build-tools-28.0.3

        - android-23
        
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

before_script:
        - chmod +x gradlew

script: "./gradlew build"

deploy:
    - provider: releases
      api_key: "$GITHUB_TOKEN"
      file : app/build/outputs/apk/releases/*
      file_glob: true
      skip_cleanup: true
      overwrite: true
      on:
          tags: true
          branch: master


